apiVersion: apps/v1
kind: Deployment
metadata:
  name: re-partners-api
  labels:
    app: re-partners-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: re-partners-api
  template:
    metadata:
      labels:
        app: re-partners-api
    spec:
      containers:
      - name: api
        image: re-partners-api:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: VERSION
          value: "1.0.0"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: re-partners-api
spec:
  type: LoadBalancer
  selector:
    app: re-partners-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

