app = "re-partners-assignment"
primary_region = "fra"

[build]
  dockerfile = "deployments/Dockerfile"

[env]
  PORT = "8080"
  VERSION = "1.0.0"
  ENVIRONMENT = "production"
  DB_ENABLED = "false"
  REDIS_ENABLED = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

