services:
  - type: pserv
    name: re-partners-postgres
    env: docker
    plan: free
    region: frankfurt
    image:
      url: postgres:15-alpine
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: re_partners

  - type: pserv
    name: re-partners-redis
    env: docker
    plan: free
    region: frankfurt
    image:
      url: redis:7-alpine
    envVars:
      - key: REDIS_PASSWORD
        generateValue: true

  - type: web
    name: re-partners-api
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./deployments/Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: PORT
        value: 8080
      - key: VERSION
        value: 1.0.0
      - key: ENVIRONMENT
        value: production
      - key: DB_ENABLED
        value: true
      - key: DB_HOST
        fromService:
          type: pserv
          name: re-partners-postgres
          property: host
      - key: DB_PORT
        fromService:
          type: pserv
          name: re-partners-postgres
          property: port
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        fromService:
          type: pserv
          name: re-partners-postgres
          envVarKey: POSTGRES_PASSWORD
      - key: DB_NAME
        value: re_partners
      - key: DB_SSLMODE
        value: disable
      - key: DB_MAX_OPEN_CONNS
        value: 25
      - key: DB_MAX_IDLE_CONNS
        value: 25
      - key: DB_CONN_MAX_LIFETIME
        value: 5m
      - key: REDIS_HOST
        fromService:
          type: pserv
          name: re-partners-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: pserv
          name: re-partners-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: pserv
          name: re-partners-redis
          envVarKey: REDIS_PASSWORD
      - key: REDIS_DB
        value: 0
      - key: REDIS_POOL_SIZE
        value: 10

