server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  idle_timeout: 60s
  shutdown_timeout: 30s

app:
  version: dev
  environment: development

database:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: re_partners
    sslmode: disable
    max_open_conns: 25
    max_idle_conns: 25
    conn_max_lifetime: 5m

cache:
  redis:
    host: localhost
    port: 6379
    password: ""
    db: 0
    pool_size: 10

logging:
  level: info
  format: json
  output: stdout

